version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./vendor:/var/www/vendor
            - ./storage:/var/www/storage
        ports:
            - "9000:9000"
        networks:
            - app-network
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

volumes:
    dbdata:
        driver: local

networks:
    app-network:
        driver: bridge
